### ISSUE TITLE
Offline First Hackathon

### ISSUE THREAD

**Issue by lewiscowper** [jsconf/wwwtf.berlin#16]
I was wondering whether anyone might want to contribute a venue, or help organise a hackathon where we introduce technologies like ServiceWorker, and AppCache, and the goal is to build a simple app, where you can switch off the network connection at some arbitrary point, and the app still works, with little to no disruption to the user.

I'd guess people might want to try and take their existing app and make it work offline, which would be cool too. It'd be good to see if people wanted to collaborate on this, and maybe we can have a speaker to introduce offline first as a design concept, and go into some of the various ways people work with offline as a state.

**Comment by weiland** [comment]
I would love helping to organise an Offline First Hackathon \o/
