### ISSUE TITLE
Add #rolemodels to event page

### ISSUE THREAD

**Issue by dianakimball** [jsconf/wwwtf.berlin#28]
Event title: #rolemodels Edition Six: Cynthia Barcomi in Conversation With Diana Kimball

Date: Wednesday, September 23
Times: Doors open at 6:30pm, fireside chat runs from 7:00pm to 8:00pm, networking from 8:00pm to 9:00pm
Event website: https://www.eventbrite.com/e/rolemodels-edition-six-cynthia-barcomi-tickets-18495849584
Tickets: RSVP required. Regular tickets are free; RailsGirls Supporter ticket is optionally available.
Location: SoundCloud HQ, Rheinsberger Str. 76/77, Berlin 10115
Organizers: Isa Sonnenfeld, Diana Kimball, and David Noël
Maximum number of registrants: 150

**Comment by rmehner** [comment]
Closed by #29, thanks @dianakimball & @janmonschke :)
