### ISSUE TITLE
The Future of the Web Summit

### ISSUE THREAD

**Issue by janl** [jsconf/wwwtf.berlin#3]
I imagine this to pair nicely with an [Extensible Web Summit](http://lanyrd.com/2014/extwebsummit-berlin/), but instead of focussing on technical platform details, we talk about a more general direction of the web.

This is mostly driven by ppk’s http://www.quirksmode.org/blog/archives/2015/05/web_vs_native_l.html and all the articles he references there. As well as this twitter conversation with me and him: https://twitter.com/ppk/status/603148192679616512

The idea is to get a few parties with competing points of views into one room and see what they can come up with. I’d like to square (at least) these areas:
- Rethinking the web (as per ppk, Jeremy Keith etc.)
- The web as an app platform (Team Ember etc.)
- The business case for the web (where the money for “competing with native” comes from. And somebody who can take VC-driven culture and more traditional business on the web and native into perspective)
- Inversion of power (decentralisation, surveillance etc)
- TBD (who else?)

I imagine roughly these people (apologies if I got your affiliations wrong):

Peter-Paul Koch (Everything)
Daniel Appelquist (WG TAG, Extensible Web)
Jeremy Keith (Indie Web)
Blaine Cook (Indie Web)

Yehuda Katz (Ember, WG TAG)
Alex Russell (ServiceWorker, WG TAG, etc.)
Jake Archibald (ServiceWorker, Google)
Remy Sharp (Practical web dev, JSbin, FullFrontal, etc.)
Thomas Fuchs (Everything)
TBD (React/React Native)

Alexander Feyerke (Hoodie, Offline-First, general web culture)
Basitan Allgeier (Decentralize.it)

TBD (Product/Business representative(s) of large news site)
etc… (please suggest more)

Sir Tim (www) (I wish!)

// these are just some people and representatives that I can think of off the top of my head. There are more people who are relevant here, please suggest them in the comments. We need to be a lot better with diversity here.

**Comment by adactio** [comment]
Looks like a fun gathering to me.

**Comment by slightlyoff** [comment]
I'm also heavily involved in the capabilities and UI aspects of web-as-first-class-apps; my team just shipped: http://blog.chromium.org/2015/03/chrome-42-beta-push-notifications_12.html

I'd love to have a conversation about that and the impacts.

Thoughts on when such a thing would happen? Have you chatted to @torgo?
