### ISSUE TITLE
Adding the ProseMirror summit

### ISSUE THREAD

**Issue by marijnh** [jsconf/wwwtf.berlin#41]
Hi, I'd like to have an event added to your list. (Sorry, can't create a PR from this device.)

Name: ProseMirror summit
Date: September 28
Time: 19:30
Location: SoundCloud HQ, Classroom room, Rheinberger Str 76/77, 10115 Berlin
Web presence: http://discuss.prosemirror.net/t/prosemirror-summit-in-berlin-on-monday-september-28/
Cost: None
Organizer: Marijn Haverbeke / @marijnjh

**Comment by rmehner** [comment]
Thanks @marijnh :)
