### ISSUE TITLE
Content too iOS focused

### ISSUE THREAD

**Issue by olafgeibig** [jsconf/wwwtf.berlin#47]
I found the contents way too much iOS focused. Minimum two apps were available for iOS, ONLY! As an android user I almost feel discriminated. Don't you guys know that in Germany there are much more Android users than iOS users? You should always link to an Android and iOS app, maybe even to Windows Mobile.

**Comment by afknapping** [comment]
Please keep in mind that people are making this on a volunteer basis. 

Feel free to suggest specific missing content. I am sure sb will gladly make a PR to bring it online.
