### ISSUE TITLE
#BerlinHero43 - Free sport charity competition

### ISSUE THREAD

**Issue by kasia0991** [jsconf/wwwtf.berlin#50]
Hello everybody!

We are organizing the first edition of #BerlinHero43 (Berlin Hero “for free”) on 17th of July in Mauerpark! It is a FREE sport event, where the main purpose is charity, and having a good time! It is a competition, where the goal is to find a person, who has the best combination of mental and physical skills. Join the event on Facebook, follow our fanpage, and check the website to get more information!!! Make sure to invite your friends, and family, everyone can join, there are no limitations! Please spread the word! Let’s make it happen! Who will be the hero? :)

Event: https://www.facebook.com/events/728012457338642/
Facebook fanpage: https://www.facebook.com/berlinhero43/
Website: http://berlinhero43.wix.com/home

**Comment by janl** [comment]
Hi, sorry this didn’t make it. Closing.
