### ISSUE TITLE
Add AlterConf Berlin

### ISSUE THREAD

**Issue by ashedryden** [jsconf/wwwtf.berlin#67]
- **date:** 13 May
- **times:** 10am-5pm
- **location:** FACTORY WORKS GMBH, RHEINSBERGER STRASSE 76/77, 10115 BERLIN
- **a link to your event website:** https://www.alterconf.com/conferences/berlin-germany
- **names of all organizers:** Ashe Dryden
- **cost:** €0-150
- **maximum number of registrants:** 130

**Comment by janl** [comment]
Finally! #25a9612

**Comment by janl** [comment]
Sorry for the delay!
