### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by janl** [jsconf/wwwtf.berlin#82]
![screen shot 2017-12-12 at 12 16 12](https://user-images.githubusercontent.com/11321/33881814-47b86dfc-df36-11e7-8dd6-e2090d4be8d1.png)

**Comment by ghost** [comment]
this should be fixed by #81, which updates `github-pages` to the latest version (in the Gemfile.lock on `gh-pages`, it's very, _very_ old)

**Comment by ghost** [comment]
@janl is this still occurring?
