### ISSUE TITLE
#causeascene Conference - Berlin

### ISSUE THREAD

**Issue by kmcrayton7** [jsconf/wwwtf.berlin#95]
Details:
Why do underrepresented & marginalized groups continue to exist in the face of unbelievable hardship? We are resilient. We adapt. We create solutions to our own problems. My solution to the lack of inclusion in tech is to organize my own conference, my own way.

#causeascene Conf is an event without borders, which is designed to be safe space for members of underrepresented and marginalized communities in tech to tell their stories. To share what they’re working on, what they’ve experienced, their tech enabled hopes and dreams. This is an opportunity for these, often sidelined and silenced, individuals to use the platform to amplify their voices, uncensored, in a very authentic manner.

When? Where?
June 4th 7:30-11:00pm CEST
Co.up Community
Adalbertstraße 8, 10999 Berlin

Cost?
25 euros

https://ti.to/kim.crayton.llc/causeascene-conference-berlin

Speakers Needed: https://goo.gl/forms/NwN7fGSnllwYGe0s2

Organizer: Kim Crayton (@kimcrayton1 & @causeasceneconf)

**Comment by ghost** [comment]
Added in 4bffab4!
